### ISSUE TITLE
Worksheet: use URIs for JSON-LD predicates (features) and objects (feature values)

### ISSUE THREAD

**Issue by minorg** [minorg/dressdiscover#316]

**Comment by minorg** [comment]
Arden will get the prefixes.

**Comment by minorg** [comment]
New JSON-LD:
``
{
    "@context": {
        "cc": "http://purl.org/costumeCore/ontology/",
        "cc:color": {
            "@type": "@id"
        },
        "cc:closure": {
            "@type": "@id"
        }
    },
    "@id": "https://dressdiscover.org/worksheet/state/New%20object%202019-5-5/",
    "cc:color": [
        "cc:CC00050",
        "cc:CC00051"
    ],
    "cc:closure": [
        "cc:CC00005",
        "cc:CC00006"
    ]
}
``

**Comment by ArdenKirkland** [comment]
new prefix, since purl.org isn't working, is "https://w3id.org/costumeCore/ontology/“

**Comment by ArdenKirkland** [comment]
(last quote is NOT a part of the link!)
